# kubectl describe pod podname 
to check any conroller is running or not

check pererameter
# kubectl explain rc  

apiVersion: v1
kind: ReplicationController
# Check all command in deatils 
# kubectl explain rc --recursive | less
metadata:
  name: sitaram
spec:
  replicas: 3  #(how many pods)
  selector:
    team: dev # only mange 3 pod hows lable team=dev
  template:   # pod deatils 
    metadata:  
      name: sirarampod
      labels:
        team: dev
    spec:
     containers:
       - name: spcontainer
         image: nginx:1.7.1
         ports:
         - containerPort: 80

# diect go on google and check the code just put name repalcation controller

# kubectl apply -f rc.yaml (yaml file name)

Delete 

# kubectl delete -f rc.yaml (Everything will delete)

If you alredy have one pod that not in any controller label name team=dev 
and we run the same file it will create 2 pod only because
we alreday have one pod team=dev

# for trubbel shooting if we want to exit one conatiner form contoller
 we need to remove the lable of container so it will exit form controller

# kubectl label pod web team- (none)

#only delet controller not pod {thsi will used for change conatller type}
  kubectl delete rc --cascade=false shubhamrc{contoller name}
  
# Kubernetes 1.3 or 1.4 only support only rolling update 
same file used erler 

apiVersion: v1
kind: ReplicationController
metadata:
  name: update-team #change name
spec:
  replicas: 3
  selector:
    app: update  #change name update here
  template:
    metadata:
      name: nginx
      labels:
        app: update #change name update here  
    spec:
      containers:
        - name: nginx
          image: nginx:1.9.1  # update image name
          ports:
            - containerPort: 80


# now time to update replication controller
kubectl rolling-update dev-tem --update-period-10s -f rc.yaml
                      {old rc name}

