apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: webwatcher
    image: afakharany/watcher:latest

# Apply the file 
kubectl apply -f pod.yaml 

#delete file 
kubectl delete -f pod.yaml


